apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-mysql" (include "ecommerce-project.fullname" .) }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "ecommerce-project.name" . }}
    tier: mysql 