nameOverride: ""
fullnameOverride: ""

image:
  php: "rileywebdev/php-store:dev7"
  dotnet: "rileywebdev/dotnet-api:latest"
  mysql: "mysql:8.0"
  sqlserver: "mcr.microsoft.com/mssql/server:2019-latest"

replicaCount: 1

service:
  type: ClusterIP
  port: 80

mysql:
  database: ecommerce
  rootPassword: ""

mssql:
  saPassword: ""

ingress:
  enabled: true 

imagePullPolicy: IfNotPresent 